services:

  nginx-gateway:
    image: nginx:alpine
    container_name: nginx-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - red-interna
    restart: always

  ms-login:
    build: ./ms-login
    container_name: ms-login
    ports:
      - "8080:8080"
    networks:
      - red-interna
    restart: unless-stopped


networks:
  red-interna:
    driver: bridge
