server {
    listen 80;
    server_name 20.164.2.29;

    # ms-grifos (VM1:8001)
    location /api/grifos/ {
        proxy_pass http://102.37.154.9:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # ms-precios (VM1:8002)
    location /api/precios/ {
        proxy_pass http://102.37.154.9:8002/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # ms-ubicacion (VM1:8003)
    location /api/ubicacion/ {
        proxy_pass http://102.37.154.9:8003/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # ms-login (VM2:8080)
    location /api/login/ {
        proxy_pass http://localhost:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
